### ISSUE TITLE
UnicodeDecodeError: 'cp932' codec can't decode byte 0x83 in position 96: illegal multibyte sequence

### ISSUE THREAD

**Issue by maeyu1110** [yasunori/Random-Forest-Example#1]
estimation.pyを実行させると
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-42-e867dbc9b68e> in <module>()
     59 
     60 if __name__ == '__main__':
---> 61     main()

<ipython-input-42-e867dbc9b68e> in main()
      9 def main():
     10     # 辞書の読み込み
---> 11     dictionary = corpus.get_dictionary(create_flg=False)
     12     # 記事の読み込み
     13     contents = corpus.get_contents()

C:\workspace\work1\corpus.py in get_dictionary(create_flg, file_name)
    132     '''
    133     if create_flg or not os.path.exists(file_name):
--> 134         # データ読み込み
    135         contents = get_contents()
    136         # 形態素解析して名詞だけ取り出す

C:\workspace\work1\corpus.py in get_contents()
    112             continue
    113         for file_name in file_list:
--> 114             if dir_name in file_name:  # LICENSE.txt とかを除くためです。。
    115                 ret[file_name] = get_file_content(DATA_DIR_PATH + dir_name + '/' + file_name)
    116 

C:\workspace\work1\corpus.py in get_file_content(file_path)
     44     '''
     45     ret = ''
　 46     with open(file_path,'r') as f:
 -->47         tmp = [line for line in f.readlines()][2:]# ライブドアコーパスが3行目から本文はじまってるから
     48         ret = ''.join(tmp)

UnicodeDecodeError: 'cp932' codec can't decode byte 0x83 in position 96: illegal multibyte sequence

というエラーがでてしまいます。対処法を教えていただきたいです

**Comment by yasunori** [comment]
ありがとうございます！！
